const AppTypes = {
  SET_USERS: "SET_USERS",
  CHOSE_USER: "CHOSE_USER",
  ON_PAGE_CHANGE: "ON_PAGE_CHANGE",
  SET_USERS_DIGEST: "SET_USERS_DIGEST",
  TOGGLE_ACTIVATION: "TOGGLE_ACTIVATION",
  SET_LOADING_STATE: "SET_LOADING_STATE"
};

export default {
  ...AppTypes
};
